# Override pour le développement avec hot-reload et volumes
# À utiliser avec: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
services:
  backend:
    build:
      context: ./backend
      target: development
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      target: development
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      # On mappe le port 4200 de la machine vers le conteneur
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - NG_ALLOWED_HOSTS=localhost,127.0.0.1,127.0.0.1:4200,localhost:4200,172.18.0.5,frontend
