services:
  mysql:
    ports:
      - "3306:3306"      

  backend:
    build:
      target: development
    ports:
      - "${HOST_BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app   
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      target: development
    ports:
      - "${HOST_FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      #- API_URL_CLIENT=http://localhost:${HOST_BACKEND_PORT}
      #- API_URL_SERVER=http://backend:3000
      - NG_ALLOWED_HOSTS=localhost,frontend,172.19.0.5,127.0.0.1
    command: npm start -- --host 0.0.0.0 --poll 2000

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - eclaireurs-network