openapi: 3.0.0
info:
  title: API Les Éclaireurs Solidaires
  version: 1.0.0
paths: 
  /mission/{missionUuid}:
    get: 
      summary : Récupère les détails d'une mission
      parameters:
        - in: path
          name: missionUuid
          schema:
            type: string
          required: true
          description: Représente l'identifiant unique d'une mission
      responses:
        200:
          description: Mission Trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  mission:
                    type: object
                    properties:

        400:
          description: Erreur de requête - le paramètre missionUuid est manquant ou invalide
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        404:
          description: Mission non trouvée

components:
  schemas:
    MissionStatus:
      type: object
      properties:
        id:
          type: integer
          description: Identifiant unique du statut de la mission
        name:
          type: string
          description: Nom du statut de la mission
      description: BROUILLON, PUBLIEE, TERMINEE, ANNULEE qui correspondent a des status precis
    Mission:
      type: object
      required:
        - uuid
        - name
        - dateStart
        - dateEnd
        - address
        - nbrVolunteerNeeded
        - organizers
        - city
        - status
        - registration
      properties:
        uuid:
          type: string
          description: Identifiant unique de la mission
        name:
          type: string
          description: Nom de la mission
        description:
          type: string
          description: Description de la mission
        dateStart:
          type: string
          format: date-time
          description: Date de début de la mission
        dateEnd:
          type: string
          format: date-time
          description: Date de fin de la mission
        status:
          type: $ref: '#/components/schemas/MissionStatus'
          description: Statut de la mission
        

  
